# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Conan
        run: |
          pip install --upgrade pip cmake
          python --version
          pip --version
          which cmake
          cmake --version
          pip install conan-package-tools
          pip install git+https://github.com/blixttech/cpt-helpers.git
          conan --version
          conan user

      - name: Build
        env:
          CONAN_USER: ""
          CONAN_CHANNEL: ""
          CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
          CONAN_DOCKER_IMAGE: "conanio/gcc7"
          CONAN_GCC_VERSIONS: "7"
          CONAN_BUILD_TYPES: "Release"
          CONAN_UPLOAD_ONLY_WHEN_STABLE: "true"
          CONAN_SYSREQUIRES_MODE: "enabled"
        run: |
          python build.py
